// <auto-generated />
namespace IEP.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OrderCreateDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderCreateDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201902011719291_OrderCreateDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
